<#
.SYNOPSIS
    Identifies inactive workstations in Active Directory and optionally
    disables them, moves them to a quarantine OU, or undoes those actions via rollback.

.DESCRIPTION
    The script scans an AD domain querying all "computer" objects
    that are NOT servers. For each workstation found, it determines the
    last logon date using two complementary attributes:

      - LastLogonDate        : replicated attribute between DCs (up to 14 days precision).
      - LastLogonTimestamp   : raw value in FileTime format, used as fallback
                               when LastLogonDate is absent.

    Computers whose last logon is before the cutoff (today - $Days days), or
    that have never logged on, are classified as inactive.

    PROTECTION AGAINST ACCIDENTAL SERVER INCLUSION:
      The script applies three independent protection layers:
        1. LDAP Filter  : excludes objects with "Server" in the operatingSystem attribute.
        2. Regex in loop: discards objects that escaped the LDAP filter but still
                          have "Server" in operatingSystem.
        3. -ExcludeServerOU: excludes all objects whose DN belongs to the specified OUs
                          or any nested sub-OU, regardless of the operatingSystem value
                          (covers empty/atypical fields).

    READ-ONLY MODE (default):
      Generates only the inventory CSV with the list of inactive workstations. No
      changes are made to AD. The CSV includes AccountEnabled and
      AlreadyInTargetOU fields to facilitate manual analyst triage.

    REMEDIATION MODE (-Remediate):
      In addition to the inventory, disables each inactive account and moves it to the
      OU specified in -TargetOU. Each action is recorded in a separate audit CSV.
      Supports -WhatIf and -Confirm for safe simulation.
      WARNING: use the AccountEnabled=False and AlreadyInTargetOU=True fields in the
      inventory to identify already-processed accounts before running remediation.

    ROLLBACK MODE (-Rollback):
      Undoes a previous remediation by reading the actions CSV generated by -Remediate
      (provided in -RollbackCsv). For each entry where Disabled=True:
        - Re-enables the account (Enable-ADAccount).
        - Attempts to move the object back to the original OU (extracted from the
          DistinguishedName recorded in the CSV).
        - If the original OU no longer exists in AD, re-enables the account and logs
          a warning — the account is NOT left disabled due to a move failure.
      Only entries where Disabled=True are processed (entries where the
      disable already failed during remediation are ignored).
      Supports -WhatIf and -Confirm for safe simulation.

    INVENTORY CSV FIELDS:
      - Domain             : FQDN of the queried domain.
      - Name               : NetBIOS computer name.
      - OperatingSystem    : operating system registered in AD.
      - LastLogonDate      : date of the last identified logon (may be $null).
      - InactiveDaysApprox : approximate days since last logon.
      - AccountEnabled     : True if the account is active in AD, False if disabled.
      - AlreadyInTargetOU  : True if the object is already in -TargetOU or a sub-OU of it;
                             False if it is in another OU; empty if -TargetOU was not
                             provided. Useful for identifying already-quarantined accounts.
      - DistinguishedName  : full DN of the object in AD.

    COMBINED INTERPRETATION OF AccountEnabled + AlreadyInTargetOU:
      False + True  -> Already properly handled. No action needed.
      True  + True  -> In quarantine but still active. Review manually.
      False + False -> Disabled but outside quarantine. Review manually.
      True  + False -> Primary candidate for remediation.

    GENERATED OUTPUTS (in C:\Temp\LogScripts\AD_Inactive_Workstations\<domain>_<timestamp>\):
      - Execution_<timestamp>.log                             : line-by-line execution log.
      - Workstations_Inactive_<domain>_<days>days.csv        : inactive workstations inventory
                                                               with all fields described above.
      - Workstations_Inactive_Actions_<timestamp>.csv        : record of all remediation actions
                                                               (only with -Remediate).
      - Workstations_Remediation_Failures_<timestamp>.csv    : computers where the disable
                                                               or move operation failed (only with
                                                               -Remediate, when there are errors).
      - Workstations_Rollback_Actions_<timestamp>.csv        : record of each rollback action
                                                               (only with -Rollback).
      - Workstations_Rollback_Failures_<timestamp>.csv       : computers where rollback failed
                                                               (only with -Rollback, when there are errors).

.PARAMETER Domain
    FQDN of the domain to scan (e.g.: corp.contoso.com).
    If omitted, the script prompts interactively via Read-Host.

.PARAMETER Days
    Number of days without logon to consider a workstation inactive.
    Default: 60 days.

.PARAMETER Remediate
    Switch. When present, disables and moves each inactive workstation to -TargetOU.
    Cannot be used together with -Rollback.
    WARNING: destructive action. Use -WhatIf for simulation before running in production.
    It is recommended to review the inventory CSV (AccountEnabled and AlreadyInTargetOU fields)
    before executing to avoid reprocessing already-handled accounts.

.PARAMETER TargetOU
    Distinguished Name (DN) of the target OU where inactive accounts will be moved.
    Required when -Remediate is used. If omitted, the script prompts interactively.
    When provided in read-only mode, the AlreadyInTargetOU field in the CSV indicates
    which computers are already in that OU.
    Example: "OU=Inactive,OU=Workstations,DC=corp,DC=contoso,DC=com"

.PARAMETER Rollback
    Switch. When present, undoes a previous remediation by reading the CSV provided in
    -RollbackCsv. Re-enables accounts and attempts to move them back to the original OU.
    Cannot be used together with -Remediate.
    WARNING: destructive action. Use -WhatIf for simulation before running in production.
    Note: rollback does not restore the previous Enabled state. Accounts that were already
    disabled before remediation will be re-enabled. Refer to the AccountEnabled field
    in the inventory CSV generated before remediation for reference.

.PARAMETER RollbackCsv
    Full path of the actions CSV file generated by a previous run with
    -Remediate (Workstations_Inactive_Actions_<timestamp>.csv).
    Required when -Rollback is used. If omitted, the script prompts interactively.

.PARAMETER ExcludeServerOU
    List of Distinguished Names (DNs) of OUs that contain servers and should be
    completely ignored in the search. Any object whose DistinguishedName contains
    one of the provided DNs will be discarded, including objects in nested sub-OUs at
    any depth level. Each OU is validated in AD before the query — invalid OUs
    generate a warning in the log and are ignored without aborting execution.
    Accepts one or more comma-separated values. Optional.
    Example: -ExcludeServerOU "OU=Servers,DC=corp,DC=contoso,DC=com","OU=Infra,DC=corp,DC=contoso,DC=com"

.PARAMETER Root
    Root path where log/CSV folders will be created. A subfolder per execution
    is created automatically with the pattern <domain>_<timestamp>.
    Default: C:\Temp\LogScripts\AD_Inactive_Workstations

.PARAMETER CsvEncoding
    Encoding for the generated CSV files. Accepted values: utf8, unicode, ascii.
    Note: in PowerShell 5.1, utf8 generates files with BOM. Use unicode if the CSV
    will be consumed by tools that do not tolerate BOM.
    Default: utf8

.EXAMPLE
    .\Verifica_Comp_Inativos_v3.4.ps1

    Runs interactively: prompts for the domain and generates only the inactive
    workstations inventory (no remediation). The AccountEnabled and AlreadyInTargetOU
    fields will be present in the CSV for triage.

.EXAMPLE
    .\Verifica_Comp_Inativos_v3.4.ps1 -Domain corp.contoso.com -Days 90 `
        -TargetOU "OU=Inactive,OU=Workstations,DC=corp,DC=contoso,DC=com" `
        -ExcludeServerOU "OU=Servers,DC=corp,DC=contoso,DC=com"

    Inventory of workstations inactive for more than 90 days, with AlreadyInTargetOU
    populated and server OUs excluded from the search.

.EXAMPLE
    .\Verifica_Comp_Inativos_v3.4.ps1 -Domain corp.contoso.com -Days 60 -Remediate `
        -TargetOU "OU=Inactive,OU=Workstations,DC=corp,DC=contoso,DC=com" `
        -ExcludeServerOU "OU=Servers,DC=corp,DC=contoso,DC=com" -WhatIf

    Simulates remediation excluding the server OU (without changing anything in AD).
    Recommended before the actual execution.

.EXAMPLE
    .\Verifica_Comp_Inativos_v3.4.ps1 -Domain corp.contoso.com -Days 60 -Remediate `
        -TargetOU "OU=Inactive,OU=Workstations,DC=corp,DC=contoso,DC=com" `
        -ExcludeServerOU "OU=Servers,DC=corp,DC=contoso,DC=com" -Confirm:$false

    Runs remediation without individual per-computer confirmation.

.EXAMPLE
    .\Verifica_Comp_Inativos_v3.4.ps1 -Domain corp.contoso.com -Rollback `
        -RollbackCsv "C:\Temp\LogScripts\AD_Inactive_Workstations\corp_contoso_com_20260305_143000\Workstations_Inactive_Actions_20260305_143000.csv" -WhatIf

    Simulates the remediation rollback (without changing anything in AD).
    Recommended before the actual execution.

.EXAMPLE
    .\Verifica_Comp_Inativos_v3.4.ps1 -Domain corp.contoso.com -Rollback `
        -RollbackCsv "C:\Temp\...\Workstations_Inactive_Actions_20260305_143000.csv" -Confirm:$false

    Runs rollback without individual per-computer confirmation.

.NOTES
    Requirements:
      - PowerShell 5.1 or later
      - ActiveDirectory module (RSAT: AD DS and AD LDS Tools)
      - Read permission in AD for inventory mode
      - Permission to disable accounts and move objects for remediation/rollback mode

    Recommended usage flow:
      1. Run in read-only mode with -TargetOU and -ExcludeServerOU to
         generate the complete inventory with all triage fields.
      2. Review the CSV — filter by AccountEnabled=True and AlreadyInTargetOU=False
         to identify the actual remediation candidates.
      3. Run with -Remediate -WhatIf to simulate the impact scope.
      4. Run with -Remediate -Confirm:$false to apply the changes.
      5. If needed, run with -Rollback pointing to the actions CSV.

    Security considerations:
      - The script does NOT delete accounts. It only disables and moves them to the quarantine OU.
      - The actions CSV serves as an audit trail for all changes made.
      - It is recommended to keep log files for at least 90 days for auditing.
      - Rollback processes only accounts that were effectively disabled (Disabled=True).
      - If the original OU no longer exists during rollback, the account is re-enabled but not
        moved. The analyst must manually relocate the objects indicated in the CSV.

    Known limitations:
      - LastLogonDate is replicated with up to 14 days latency between DCs. Computers
        with a recent logon on another DC may falsely appear as inactive.
      - The LDAP filter and the regex layer exclude objects with "Server" in the
        operatingSystem attribute, but systems with atypical names or empty fields may not be
        filtered — use -ExcludeServerOU to cover those cases.
      - Rollback does not restore the previous Enabled state of the account. Accounts already
        disabled before remediation will be re-enabled. Refer to the AccountEnabled field
        in the inventory CSV generated before remediation.

    Version history:
      v3.4f- 2026-03-05 - Documentation completely revised: description of the three
                          server protection layers, inventory CSV fields table,
                          AccountEnabled + AlreadyInTargetOU interpretation matrix,
                          recommended 5-step usage flow,
                          examples updated for command-line usage.
      v3.4e- 2026-03-05 - Added AccountEnabled and AlreadyInTargetOU fields to the
                          inventory CSV. AccountEnabled reflects the AD Enabled attribute.
                          AlreadyInTargetOU indicates whether the object is already in
                          -TargetOU or a sub-OU of it (null if -TargetOU not provided).
      v3.4d- 2026-03-05 - Bugfix: param block at the script root scope and splatting
                          @PSBoundParameters in the direct execution trigger. Fixes
                          the root cause by which no command-line parameters were
                          passed through to Invoke-InactiveWorkstations.
      v3.4c- 2026-03-05 - Bugfix: ExcludeServerOU filter fixed from EndsWith
                          to Contains, ensuring exclusion of objects in nested sub-OUs
                          at any depth level.
      v3.4b- 2026-03-05 - Bugfix: $dc explicitly cast to [string] to
                          avoid binding error with ADPropertyValueCollection when
                          passing the hostname to the -Server parameter of AD cmdlets.
      v3.4a- 2026-03-05 - Added -ExcludeServerOU parameter ([string[]]): accepts
                          one or more OUs whose objects (and all sub-OUs) are
                          excluded from the search by DN. Each OU is validated in AD before
                          the query. Third protection layer against servers,
                          complementary to the LDAP filter and OS regex check.
      v3.3 - 2026-03-05 - Added rollback mode (-Rollback / -RollbackCsv):
                          re-enables accounts and restores original OU based on the
                          audit CSV generated by -Remediate. If the original OU no longer
                          exists, re-enables the account and logs a warning. Support for
                          -WhatIf and -Confirm. Separate rollback audit and failure CSVs.
      v3.2 - 2026-03-05 - Added target OU validation before the main loop.
                          Prevents partial failures (account disabled but not moved)
                          caused by an invalid or inaccessible OU.
      v3.1 - 2026-03-03 - Added dedicated remediation failure CSV
                          (Workstations_Remediation_Failures_<timestamp>.csv) with count
                          in the final log, for quick access to computers where the
                          disable or move to the target OU did not succeed.
      v3   - 2026-03-03 - Fixes: [CmdletBinding] repositioned, protection against
                          $null in $computers, $doRemediate as local bool,
                          Read-Host moved outside the loop, -ResultSetSize $null
                          restored, actions CSV with full fields, trigger condition
                          fixed to not fire on dot-source.
      v1   - Initial version.

    Author : Marco Farias - NEXA

#>

# param block at the script scope: required for PowerShell to recognize
# command-line arguments and make them available in $PSBoundParameters,
# allowing automatic forwarding to Invoke-InactiveWorkstations via splatting.
[CmdletBinding(SupportsShouldProcess=$true, ConfirmImpact='High')]
param(
    [Parameter(Position=0, Mandatory=$false)] [string]$Domain,
    [int]$Days = 60,
    [switch]$Remediate,
    [string]$TargetOU,
    [switch]$Rollback,
    [string]$RollbackCsv,
    [string[]]$ExcludeServerOU = @(),
    [string]$Root = 'C:\Temp\LogScripts\AD_Inactive_Workstations',
    [ValidateSet('utf8','unicode','ascii')] [string]$CsvEncoding = 'utf8'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ==============================================================================
# HELPER FUNCTIONS
# ==============================================================================

function Initialize-Folders {
<#
.SYNOPSIS
    Creates the folder structure to store logs and CSVs for the execution.
.DESCRIPTION
    Ensures the root folder exists and creates a unique subfolder per execution,
    named with the domain and current timestamp (yyyyMMdd_HHmmss).
    Returns the full path of the created subfolder.
.PARAMETER Root
    Root folder path. Created automatically if it does not exist.
.PARAMETER DomainTag
    Domain identifier (dots replaced by underscores) used
    to compose the execution subfolder name.
#>
    param(
        [string]$Root = 'C:\Temp\LogScripts\AD_Inactive_Workstations',
        [string]$DomainTag
    )
    if (-not (Test-Path $Root)) { New-Item -Path $Root -ItemType Directory -Force | Out-Null }
    $runTag = "{0}_{1}" -f $DomainTag, (Get-Date -Format 'yyyyMMdd_HHmmss')
    $runDir = Join-Path $Root $runTag
    New-Item -Path $runDir -ItemType Directory -Force | Out-Null
    return $runDir
}

function Write-Log {
<#
.SYNOPSIS
    Writes a log line to the console and file simultaneously.
.DESCRIPTION
    Formats the message with timestamp and level (INFO/WARN/ERROR/OK),
    displays to the console via Write-Host and appends to the execution log file.
.PARAMETER Message
    Text of the message to be recorded.
.PARAMETER LogFile
    Full path of the destination log file (.log).
.PARAMETER Level
    Message severity. Values: INFO (default), WARN, ERROR, OK.
#>
    param(
        [Parameter(Mandatory)] [string]$Message,
        [Parameter(Mandatory)] [string]$LogFile,
        [ValidateSet('INFO','WARN','ERROR','OK')] [string]$Level = 'INFO'
    )
    $line = "{0} [{1}] {2}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Level, $Message
    Write-Host $line
    Add-Content -Path $LogFile -Value $line
}

function Get-LastLogonDate {
<#
.SYNOPSIS
    Returns the last logon date of an AD computer object.
.DESCRIPTION
    Attempts to obtain the last logon date using two attributes, in order of
    preference:

      1. LastLogonDate  : already converted to [DateTime], replicated between DCs
                          (up to 14 days latency). Used when available.
      2. LastLogonTimestamp : raw value in Windows FileTime format (Int64).
                              Converted via [DateTime]::FromFileTime().
                              Used as fallback when LastLogonDate is absent.

    Returns $null if neither attribute is available (computer has never
    logged on or attributes have not been replicated).
.PARAMETER ComputerObj
    ADComputer object returned by Get-ADComputer with the
    LastLogonDate and LastLogonTimestamp properties already loaded.
#>
    param($ComputerObj)

    # Priority 1: LastLogonDate (already [DateTime], replicated between DCs)
    if ($ComputerObj.LastLogonDate) { return $ComputerObj.LastLogonDate }

    # Priority 2: LastLogonTimestamp (raw FileTime, not replicated — local value of the queried DC)
    if ($null -ne $ComputerObj.LastLogonTimestamp -and $ComputerObj.LastLogonTimestamp -ne 0) {
        try { return [DateTime]::FromFileTime([int64]$ComputerObj.LastLogonTimestamp) } catch { return $null }
    }

    # No logon data available
    return $null
}

# ==============================================================================
# ROLLBACK FUNCTION
# ==============================================================================

function Invoke-Rollback {
<#
.SYNOPSIS
    Undoes a previous remediation by reading the actions CSV generated by -Remediate.
.DESCRIPTION
    For each row in the CSV where Disabled=True:
      1. Re-enables the account in AD (Enable-ADAccount).
      2. Extracts the original OU from the DistinguishedName recorded in the CSV (removes the
         initial CN= component to get the parent OU path).
      3. Checks if the original OU still exists. If so, moves the object back.
         If not, keeps the account re-enabled and logs a warning — the account is NOT
         left disabled due to a move failure.
    Rows where Disabled=False are ignored (the disable already failed
    in the original remediation, so there is nothing to undo).
    Supports -WhatIf and -Confirm natively via CmdletBinding.
.PARAMETER CsvPath
    Path of the actions CSV generated by a previous run with -Remediate.
.PARAMETER Dc
    Hostname of the DC to be used in AD operations.
.PARAMETER LogFile
    Path of the log file for this rollback execution.
.PARAMETER CsvRollbackActions
    Path of the rollback actions audit CSV.
.PARAMETER CsvRollbackFailed
    Path of the rollback failures exclusive CSV.
.PARAMETER CsvEncoding
    Encoding for writing output CSVs.
.PARAMETER PSCmdlet
    PSCmdlet object from the calling function, required to propagate ShouldProcess.
#>
    [CmdletBinding(SupportsShouldProcess=$true, ConfirmImpact='High')]
    param(
        [Parameter(Mandatory)] [string]$CsvPath,
        [Parameter(Mandatory)] [string]$Dc,
        [Parameter(Mandatory)] [string]$LogFile,
        [Parameter(Mandatory)] [string]$CsvRollbackActions,
        [Parameter(Mandatory)] [string]$CsvRollbackFailed,
        [Parameter(Mandatory)] [string]$CsvEncoding,
        [Parameter(Mandatory)] $CallerCmdlet
    )

    # Load the actions CSV from the original remediation
    $actions = @(Import-Csv -Path $CsvPath -Encoding $CsvEncoding)
    $total   = $actions.Count
    Write-Log -LogFile $LogFile -Level INFO -Message "Rollback | $total entries read from: $CsvPath"

    # Filter only entries where the disable was effectively performed
    $toProcess = @($actions | Where-Object { $_.Disabled -eq 'True' })
    $skipped   = $total - $toProcess.Count
    Write-Log -LogFile $LogFile -Level INFO -Message "Rollback | $($toProcess.Count) accounts to re-enable | $skipped ignored (Disabled=False)"

    $firstRbActions = $true; $firstRbFailed = $true
    $idx = 0; $successCount = 0; $failedCount = 0

    foreach ($entry in $toProcess) {
        $idx++
        $dn   = $entry.DistinguishedName
        $name = $entry.Name
        Write-Log -LogFile $LogFile -Level INFO -Message "Rollback $idx of $($toProcess.Count) : $name"

        # Extracts the original OU: removes the first component (CN=<name>,) from the original DN.
        # Example: "CN=PC01,OU=IT,DC=corp,DC=com" -> "OU=IT,DC=corp,DC=com"
        $originalOU = $dn -replace '^CN=[^,]+,', ''

        if (-not $CallerCmdlet.ShouldProcess($dn, "Re-enable and move back to $originalOU")) { continue }

        $reenabled   = $false
        $movedBack   = $false
        $ouMissing   = $false
        $err         = $null

        # The object was moved to the quarantine OU; its current DN uses the same CN
        # but with the TargetOU path recorded in the CSV
        $currentDN = "CN=$name,$($entry.TargetOU)"

        try {
            # Step 1: re-enable the account using the current DN (in the quarantine OU)
            Enable-ADAccount -Identity $currentDN -Confirm:$false
            $reenabled = $true
            Write-Log -LogFile $LogFile -Level OK -Message "Re-enabled: $name"
        } catch {
            $err = $_.Exception.Message
            Write-Log -LogFile $LogFile -Level ERROR -Message "Failed to re-enable $name | $err"
        }

        # Step 2: attempts to move back to the original OU (only if re-enable succeeded)
        if ($reenabled) {
            try {
                Get-ADOrganizationalUnit -Identity $originalOU -Server $Dc -ErrorAction Stop | Out-Null
            } catch {
                # Original OU no longer exists — logs a warning but keeps account active
                $ouMissing = $true
                Write-Log -LogFile $LogFile -Level WARN -Message "Original OU not found for $name ($originalOU). Account re-enabled but not moved. Manual relocation required."
            }

            if (-not $ouMissing) {
                try {
                    Move-ADObject -Identity $currentDN -TargetPath $originalOU -Confirm:$false
                    $movedBack = $true
                    Write-Log -LogFile $LogFile -Level OK -Message "Moved back: $name -> $originalOU"
                } catch {
                    $err = $_.Exception.Message
                    Write-Log -LogFile $LogFile -Level ERROR -Message "Failed to move $name back | $err"
                }
            }
        }

        # Determines consolidated result
        $rollbackOk = $reenabled -and ($movedBack -or $ouMissing)
        if ($rollbackOk) { $successCount++ } else { $failedCount++ }

        # Rollback audit
        $rbObj = [pscustomobject]@{
            Domain            = $entry.Domain
            Name              = $name
            DistinguishedName = $dn
            OriginalOU        = $originalOU
            Reenabled         = $reenabled
            MovedBack         = $movedBack
            OUMissing         = $ouMissing
            Error             = $err
            Timestamp         = (Get-Date)
        }
        $rbCsv = $rbObj | ConvertTo-Csv -NoTypeInformation
        if ($firstRbActions) {
            $rbCsv | Out-File -FilePath $CsvRollbackActions -Encoding $CsvEncoding -Force
            $firstRbActions = $false
        } else {
            $rbCsv | Select-Object -Skip 1 | Out-File -FilePath $CsvRollbackActions -Encoding $CsvEncoding -Append
        }

        # Failure CSV: only when re-enable failed (missing OU is not a failure)
        if (-not $reenabled) {
            $failCsv = $rbObj | ConvertTo-Csv -NoTypeInformation
            if ($firstRbFailed) {
                $failCsv | Out-File -FilePath $CsvRollbackFailed -Encoding $CsvEncoding -Force
                $firstRbFailed = $false
            } else {
                $failCsv | Select-Object -Skip 1 | Out-File -FilePath $CsvRollbackFailed -Encoding $CsvEncoding -Append
            }
        }
    }

    $summary = "Rollback completed | Success: $successCount | Failures: $failedCount | Ignored: $skipped"
    if ($failedCount -gt 0) { $summary += " | Check: $CsvRollbackFailed" }
    Write-Log -LogFile $LogFile -Level OK -Message $summary
}

# ==============================================================================
# MAIN FUNCTION
# ==============================================================================

function Invoke-InactiveWorkstations {
<#
.SYNOPSIS
    Scans an AD domain and identifies/remediates inactive workstations.
.DESCRIPTION
    Queries all computer objects of the workstation type (excludes servers
    by the operatingSystem attribute), evaluates the last logon date of each one
    and classifies as inactive every computer that has not logged on within
    the period defined by -Days. Generates an inventory CSV and, optionally,
    disables and moves the inactive accounts to a quarantine OU.
#>
    [CmdletBinding(SupportsShouldProcess=$true, ConfirmImpact='High')]
    param(
        [Parameter(Position=0, Mandatory=$false)] [string]$Domain,
        [int]$Days = 60,
        [switch]$Remediate,
        [string]$TargetOU,
        [switch]$Rollback,
        [string]$RollbackCsv,
        [string[]]$ExcludeServerOU = @(),
        [string]$Root = 'C:\Temp\LogScripts\AD_Inactive_Workstations',
        [ValidateSet('utf8','unicode','ascii')] [string]$CsvEncoding = 'utf8'
    )

    # ------------------------------------------------------------------
    # PREREQUISITES
    # ------------------------------------------------------------------

    # -Remediate and -Rollback are mutually exclusive
    if ($Remediate -and $Rollback) {
        throw '-Remediate and -Rollback cannot be used simultaneously.'
    }

    # Check and import the ActiveDirectory module (requires RSAT installed)
    if (-not (Get-Module -Name ActiveDirectory)) {
        try { Import-Module ActiveDirectory -ErrorAction Stop } catch { throw "ActiveDirectory module not found." }
    }

    # Prompts for domain interactively if not passed as parameter
    if ([string]::IsNullOrWhiteSpace($Domain)) {
        $Domain = Read-Host 'Enter the domain (FQDN) to scan (e.g.: corp.contoso.com)'
        if ([string]::IsNullOrWhiteSpace($Domain)) { throw 'Domain not provided.' }
    }

    # ------------------------------------------------------------------
    # PATH AND LOG INITIALIZATION
    # ------------------------------------------------------------------

    # Cutoff date: computers without logon before this date are inactive
    $cutoff = (Get-Date).AddDays(-$Days)

    # Replaces dots with underscores for safe use in file/folder names
    $domainTag = ($Domain -replace '\.', '_')

    $runDir              = Initialize-Folders -Root $Root -DomainTag $domainTag
    $runTs               = Get-Date -Format 'yyyyMMdd_HHmmss'
    $logFile             = Join-Path $runDir ("Execution_{0}.log"                              -f $runTs)
    $csvInventory        = Join-Path $runDir ("Workstations_Inactive_{0}_{1}days.csv"          -f $domainTag, $Days)
    $csvActions          = Join-Path $runDir ("Workstations_Inactive_Actions_{0}.csv"          -f $runTs)
    $csvFailed           = Join-Path $runDir ("Workstations_Remediation_Failures_{0}.csv"      -f $runTs)
    $csvRollbackActions  = Join-Path $runDir ("Workstations_Rollback_Actions_{0}.csv"          -f $runTs)
    $csvRollbackFailed   = Join-Path $runDir ("Workstations_Rollback_Failures_{0}.csv"         -f $runTs)

    Write-Log -LogFile $logFile -Level INFO -Message "Start | Domain=$Domain | Days=$Days | Cutoff=$($cutoff.ToString('yyyy-MM-dd')) | Excluded OUs=$($ExcludeServerOU.Count)"

    # ------------------------------------------------------------------
    # ACTIVE DIRECTORY CONNECTION
    # ------------------------------------------------------------------

    # Automatically discovers the nearest DC for the target domain
    try {
        # HostName returns ADPropertyValueCollection — [string] forces safe conversion to string
        $dc         = [string](Get-ADDomainController -Discover -DomainName $Domain).HostName
        $searchBase = (Get-ADDomain -Identity $Domain).DistinguishedName
    } catch {
        Write-Log -LogFile $logFile -Level ERROR -Message "Error connecting to AD: $($_.Exception.Message)"
        throw
    }

    # ------------------------------------------------------------------
    # VALIDATION AND NORMALIZATION OF EXCLUDED OUs
    # ------------------------------------------------------------------

    # Normalizes each DN to lowercase for case-insensitive comparison.
    # Validates the existence of each OU in AD — invalid OUs generate WARN and are ignored
    # (they do not abort execution, as they are an additional protection, not a mandatory block).
    $excludedOUNorm = [System.Collections.Generic.List[string]]::new()
    foreach ($ouDN in $ExcludeServerOU) {
        if ([string]::IsNullOrWhiteSpace($ouDN)) { continue }
        try {
            Get-ADOrganizationalUnit -Identity $ouDN -Server $dc -ErrorAction Stop | Out-Null
            $excludedOUNorm.Add($ouDN.ToLower())
            Write-Log -LogFile $logFile -Level INFO -Message "Validated excluded OU: $ouDN"
        } catch {
            Write-Log -LogFile $logFile -Level WARN -Message "Excluded OU not found in AD (will be ignored): $ouDN | $($_.Exception.Message)"
        }
    }

    # ------------------------------------------------------------------
    # ROLLBACK MODE — executes and exits without querying AD
    # ------------------------------------------------------------------

    if ($Rollback) {
        # Prompts for CSV interactively if not passed as parameter
        if ([string]::IsNullOrWhiteSpace($RollbackCsv)) {
            $RollbackCsv = Read-Host 'Enter the path of the remediation actions CSV (Workstations_Inactive_Actions_*.csv)'
        }
        if ([string]::IsNullOrWhiteSpace($RollbackCsv)) {
            Write-Log -LogFile $logFile -Level ERROR -Message 'Rollback CSV path not provided. Operation cancelled.'
            return
        }
        if (-not (Test-Path $RollbackCsv)) {
            Write-Log -LogFile $logFile -Level ERROR -Message "Rollback CSV not found: $RollbackCsv"
            return
        }

        Write-Log -LogFile $logFile -Level INFO -Message "Rollback start | CSV=$RollbackCsv"

        Invoke-Rollback `
            -CsvPath            $RollbackCsv `
            -Dc                 ($dc | Select-Object -First 1) `
            -LogFile            $logFile `
            -CsvRollbackActions $csvRollbackActions `
            -CsvRollbackFailed  $csvRollbackFailed `
            -CsvEncoding        $CsvEncoding `
            -CallerCmdlet       $PSCmdlet

        return
    }

    # ------------------------------------------------------------------
    # AD QUERY
    # ------------------------------------------------------------------

    # Properties loaded per object — minimizes network traffic
    $props = @(
        'Name','DNSHostName','OperatingSystem','OperatingSystemVersion',
        'LastLogonTimestamp','LastLogonDate',
        'whenCreated','whenChanged','Enabled',
        'DistinguishedName','CanonicalName','PasswordLastSet'
    )

    # LDAP filter: only computer objects that do NOT have "Server" in the operatingSystem field
    # Note: the heuristic in the loop below complements this filter for atypical cases
    $ldap = '(&(objectCategory=computer)(!(operatingSystem=*Server*)))'

    Write-Log -LogFile $logFile -Level INFO -Message "Searching computers in AD..."

    # @() ensures array even if the query returns zero or a single object
    # -ResultSetSize $null removes the default limit and returns all objects
    $computers = @(Get-ADComputer -Server $dc -SearchBase $searchBase -LDAPFilter $ldap -Properties $props -ResultPageSize 500 -ResultSetSize $null)

    Write-Log -LogFile $logFile -Level INFO -Message "$($computers.Count) objects returned by AD before exclusion filters."

    # Filters objects whose DN is contained in any excluded OU (or its sub-OUs).
    # Uses .Contains() to cover nested sub-OUs at any level:
    #   DN "CN=SRV01,OU=SQL,OU=Servers,DC=corp,DC=com" contains "ou=servers,dc=corp,dc=com"
    #   DN "CN=SRV02,OU=Servers,DC=corp,DC=com"        contains "ou=servers,dc=corp,dc=com"
    # The prefixed comma ensures no false positive from partial OU name:
    #   "ou=servers2,..." would not be blocked by an exclusion of "ou=servers,..."
    if ($excludedOUNorm.Count -gt 0) {
        $beforeFilter = $computers.Count
        $computers = @($computers | Where-Object {
            $dnLower = $_.DistinguishedName.ToLower()
            $blocked = $false
            foreach ($ouNorm in $excludedOUNorm) {
                if ($dnLower.Contains(",$ouNorm")) {
                    $blocked = $true; break
                }
            }
            -not $blocked
        })
        $filteredByOU = $beforeFilter - $computers.Count
        Write-Log -LogFile $logFile -Level INFO -Message "$filteredByOU object(s) excluded by -ExcludeServerOU. $($computers.Count) remaining for analysis."
    }

    # ------------------------------------------------------------------
    # EXECUTION AND REMEDIATION CONTROLS
    # ------------------------------------------------------------------

    $firstInventory = $true; $firstActions = $true; $firstFailed = $true
    $foundWorkstations = 0; $skippedServers = 0; $inactiveCount = 0; $failedCount = 0; $idx = 0
    $total = $computers.Count

    # Uses local bool variable to avoid reassigning the original [switch] parameter
    $doRemediate = $Remediate.IsPresent

    # Prompts for target OU BEFORE the loop to avoid interrupting processing per iteration
    if ($doRemediate -and [string]::IsNullOrWhiteSpace($TargetOU)) {
        $TargetOU = Read-Host 'Enter the target OU (DN)'
        if ([string]::IsNullOrWhiteSpace($TargetOU)) {
            Write-Log -LogFile $logFile -Level ERROR -Message 'Target OU is empty. Remediation cancelled.'
            $doRemediate = $false
        }
    }

    # Validates whether the target OU exists in AD before starting the loop.
    # Prevents an invalid OU from only being discovered on the first Move-ADObject attempt,
    # which would result in a partial failure (account disabled but not moved) for each object.
    if ($doRemediate) {
        try {
            Get-ADOrganizationalUnit -Identity $TargetOU -Server $dc -ErrorAction Stop | Out-Null
            Write-Log -LogFile $logFile -Level INFO -Message "Target OU validated: $TargetOU"
        } catch {
            Write-Log -LogFile $logFile -Level ERROR -Message "Target OU invalid or inaccessible: $TargetOU | $($_.Exception.Message)"
            Write-Log -LogFile $logFile -Level ERROR -Message 'Remediation cancelled. No changes were made to AD.'
            $doRemediate = $false
        }
    }

    # ------------------------------------------------------------------
    # MAIN PROCESSING
    # ------------------------------------------------------------------

    foreach ($c in $computers) {
        $idx++
        Write-Log -LogFile $logFile -Level INFO -Message "Processing $idx of $total : $($c.Name)"

        # Additional safety: ignores objects that the LDAP filter may not have excluded
        if ($c.OperatingSystem -and $c.OperatingSystem -match 'Server') { $skippedServers++; continue }

        $foundWorkstations++
        $lastLogon = Get-LastLogonDate -ComputerObj $c

        # Inactive if never logged on ($null) or if last logon was before the cutoff
        $isInactive = ($null -eq $lastLogon) -or ($lastLogon -lt $cutoff)

        if ($isInactive) {
            $inactiveCount++

            # Inventory record — selected fields for the report
            $row = [pscustomobject]@{
                Domain               = $Domain
                Name                 = $c.Name
                OperatingSystem      = $c.OperatingSystem
                LastLogonDate        = $lastLogon
                InactiveDaysApprox   = if ($lastLogon) {[int]((New-TimeSpan -Start $lastLogon -End (Get-Date)).TotalDays)} else {$null}
                AccountEnabled       = $c.Enabled
                AlreadyInTargetOU    = if ([string]::IsNullOrWhiteSpace($TargetOU)) { $null } else { $c.DistinguishedName.ToLower().Contains(",$($TargetOU.ToLower())") }
                DistinguishedName    = $c.DistinguishedName
            }

            # Incremental export: writes header only on the first row,
            # then only data to avoid duplicate headers in the CSV
            $csvText = $row | ConvertTo-Csv -NoTypeInformation
            if ($firstInventory) {
                $csvText | Out-File -FilePath $csvInventory -Encoding $CsvEncoding -Force
                $firstInventory = $false
            } else {
                $csvText | Select-Object -Skip 1 | Out-File -FilePath $csvInventory -Encoding $CsvEncoding -Append
            }

            # ----------------------------------------------------------
            # REMEDIATION (only with -Remediate)
            # ----------------------------------------------------------
            # ShouldProcess enables native -WhatIf and -Confirm support in PowerShell
            if ($doRemediate -and $PSCmdlet.ShouldProcess($c.DistinguishedName, "Disable and move to $TargetOU")) {
                $disabled = $false; $moved = $false; $err = $null

                try {
                    # Step 1: disable the account in AD
                    Disable-ADAccount -Identity $c.DistinguishedName -Confirm:$false
                    $disabled = $true

                    # Step 2: move the object to the quarantine OU
                    # The original DN is still valid after Disable-ADAccount (only the password/flag changes)
                    Move-ADObject -Identity $c.DistinguishedName -TargetPath $TargetOU -Confirm:$false
                    $moved = $true

                    Write-Log -LogFile $logFile -Level OK -Message "Remediated: $($c.Name)"
                } catch {
                    # Partial failure: records the error but continues the loop for the remaining objects
                    $err = $_.Exception.Message
                    Write-Log -LogFile $logFile -Level ERROR -Message "Failure: $($c.Name) | $err"
                }

                # Audit trail: records the result of each remediation attempt
                # Includes Domain and DistinguishedName for traceability in multi-domain environments
                $actionObj = [pscustomobject]@{
                    Domain            = $Domain
                    Name              = $c.Name
                    DistinguishedName = $c.DistinguishedName
                    Disabled          = $disabled
                    Moved             = $moved
                    TargetOU          = $TargetOU
                    Error             = $err
                    Timestamp         = (Get-Date)
                }
                $actCsv = $actionObj | ConvertTo-Csv -NoTypeInformation
                if ($firstActions) {
                    $actCsv | Out-File -FilePath $csvActions -Encoding $CsvEncoding -Force; $firstActions = $false
                } else {
                    $actCsv | Select-Object -Skip 1 | Out-File -FilePath $csvActions -Encoding $CsvEncoding -Append
                }

                # Failure CSV: records only computers where at least one step failed
                if (-not $disabled -or -not $moved) {
                    $failedCount++
                    $failCsv = $actionObj | ConvertTo-Csv -NoTypeInformation
                    if ($firstFailed) {
                        $failCsv | Out-File -FilePath $csvFailed -Encoding $CsvEncoding -Force; $firstFailed = $false
                    } else {
                        $failCsv | Select-Object -Skip 1 | Out-File -FilePath $csvFailed -Encoding $CsvEncoding -Append
                    }
                }
            }
        }
    }

    $summary = "Completed | Inactive: $inactiveCount of $foundWorkstations workstations analyzed."
    if ($doRemediate) {
        $summary += " | Remediation failures: $failedCount"
        if ($failedCount -gt 0) {
            $summary += " | Check: $csvFailed"
        }
    }
    Write-Log -LogFile $logFile -Level OK -Message $summary
}

# ==============================================================================
# DIRECT EXECUTION TRIGGER
# Executes the main function only when the script is called directly.
# When dot-sourced (. .\script.ps1), only loads the functions without executing,
# allowing the analyst to call Invoke-InactiveWorkstations manually
# with the desired parameters.
# $PSBoundParameters automatically forwards all parameters received
# on the command line to the function, without needing to list them manually.
# ==============================================================================
if ($PSCommandPath -and $MyInvocation.InvocationName -ne '.') {
    Invoke-InactiveWorkstations @PSBoundParameters
}
